/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package de.esterlino.timeplater.view.workweektable;

import de.esterlino.timeplater.utils.DateTimeFormatUtils;
import de.esterlino.timeplater.view.content.Content;
import de.esterlino.timeplater.worktimes.model.WorkTime;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.time.LocalTime;
import java.time.format.DateTimeParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.UIManager;

/**
 *
 * @author Julien
 */
public class WorkTimeColumnPanel extends JPanel implements Content {

    private WorkTime workTime = null;
    private boolean editMode;

    /**
     * Creates new form WorkTimePanel
     */
    public WorkTimeColumnPanel(final WorkTime workTime, final boolean editMode) {
        this.workTime = workTime;
        this.editMode = editMode;

        initComponents();
        updateControls();
    }

    public WorkTimeColumnPanel() {
        this(null, false);
    }

    public void setAllBackgrounds(final Color bg) {
        setBackground(bg);
        startTimeLabel.setBackground(bg);
        endTimeLabel.setBackground(bg);
        startEndLabelSeparatorLabel.setBackground(bg);
        workDurationPanel.setBackground(bg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        GridBagConstraints gridBagConstraints;

        startTimeTextField = new JTextField();
        startEndTextFieldSeparatorLabel = new JLabel();
        endTimeTextField = new JTextField();
        startTimeLabel = new JLabel();
        startEndLabelSeparatorLabel = new JLabel();
        endTimeLabel = new JLabel();
        workDurationPanel = new JPanel();
        workDurationPrefixLabel = new JLabel();
        workDurationLabel = new JLabel();
        workDurationPostfixLabel = new JLabel();

        setBackground(UIManager.getDefaults().getColor("Table.background"));
        setLayout(new GridBagLayout());

        startTimeTextField.setColumns(3);
        startTimeTextField.setHorizontalAlignment(JTextField.CENTER);
        startTimeTextField.setText("00:00");
        startTimeTextField.setNextFocusableComponent(endTimeTextField);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        add(startTimeTextField, gridBagConstraints);

        startEndTextFieldSeparatorLabel.setBackground(UIManager.getDefaults().getColor("Table.background"));
        startEndTextFieldSeparatorLabel.setText("-");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new Insets(3, 7, 5, 4);
        add(startEndTextFieldSeparatorLabel, gridBagConstraints);

        endTimeTextField.setColumns(3);
        endTimeTextField.setHorizontalAlignment(JTextField.CENTER);
        endTimeTextField.setText("00:00");
        endTimeTextField.setMinimumSize(new Dimension(23, 22));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        add(endTimeTextField, gridBagConstraints);

        startTimeLabel.setBackground(UIManager.getDefaults().getColor("Table.background"));
        startTimeLabel.setText("00:00");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new Insets(3, 7, 5, 4);
        add(startTimeLabel, gridBagConstraints);

        startEndLabelSeparatorLabel.setBackground(UIManager.getDefaults().getColor("Table.background"));
        startEndLabelSeparatorLabel.setText("-");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new Insets(3, 7, 5, 4);
        add(startEndLabelSeparatorLabel, gridBagConstraints);

        endTimeLabel.setBackground(UIManager.getDefaults().getColor("Table.background"));
        endTimeLabel.setText("00:00");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new Insets(3, 7, 5, 4);
        add(endTimeLabel, gridBagConstraints);

        workDurationPanel.setBackground(UIManager.getDefaults().getColor("Table.background"));
        workDurationPanel.setLayout(new GridBagLayout());

        workDurationPrefixLabel.setBackground(UIManager.getDefaults().getColor("Table.background"));
        workDurationPrefixLabel.setText("(");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new Insets(3, 7, 5, 0);
        workDurationPanel.add(workDurationPrefixLabel, gridBagConstraints);

        workDurationLabel.setBackground(UIManager.getDefaults().getColor("Table.background"));
        workDurationLabel.setText("00:00");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new Insets(3, 0, 5, 0);
        workDurationPanel.add(workDurationLabel, gridBagConstraints);

        workDurationPostfixLabel.setBackground(UIManager.getDefaults().getColor("Table.background"));
        workDurationPostfixLabel.setText(")");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new Insets(3, 0, 5, 4);
        workDurationPanel.add(workDurationPostfixLabel, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        add(workDurationPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel endTimeLabel;
    private JTextField endTimeTextField;
    private JLabel startEndLabelSeparatorLabel;
    private JLabel startEndTextFieldSeparatorLabel;
    private JLabel startTimeLabel;
    private JTextField startTimeTextField;
    private JLabel workDurationLabel;
    private JPanel workDurationPanel;
    private JLabel workDurationPostfixLabel;
    private JLabel workDurationPrefixLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setEnabled(final boolean enabled) {
        super.setEnabled(enabled);
        startTimeLabel.setEnabled(enabled);
        startEndLabelSeparatorLabel.setEnabled(enabled);
        endTimeLabel.setEnabled(enabled);
        workDurationLabel.setEnabled(enabled);
        workDurationPrefixLabel.setEnabled(enabled);
        workDurationPostfixLabel.setEnabled(enabled);
    }

    @Override
    public Object getContent() {

        String startTimeString;
        String endTimeString;

        if (editMode) {
            startTimeString = startTimeTextField.getText();
            endTimeString = endTimeTextField.getText();
        } else {
            startTimeString = startTimeLabel.getText();
            endTimeString = endTimeLabel.getText();
        }

        LocalTime startTime;
        LocalTime endTime;

        try {
            startTimeString = DateTimeFormatUtils.padTimeStringWithLeadingZeroIfNecessary(startTimeString);
            startTime = LocalTime.parse(startTimeString);
        } catch (DateTimeParseException e) {
            Logger.getLogger(WorkTimeColumnPanel.class.getName() + ".getContent()").log(Level.WARNING, String.format(
                    "Could not parse start-time from given Text: \"%s\"",
                    editMode
                            ? startTimeTextField.getText()
                            : startTimeLabel.getText()),
                    e);

            startTime = workTime.getStartTime();
            endTime = workTime.getEndTime();

            return new WorkTime(startTime, endTime);
        }

        try {
            endTimeString = DateTimeFormatUtils.padTimeStringWithLeadingZeroIfNecessary(endTimeString);
            endTime = LocalTime.parse(endTimeString);
        } catch (DateTimeParseException e) {
            Logger.getLogger(WorkTimeColumnPanel.class.getName() + ".getContent()").log(Level.WARNING, String.format(
                    "Could not parse end-time from given Text: \"%s\"",
                    editMode
                            ? endTimeTextField.getText()
                            : endTimeLabel.getText()),
                    e);

            startTime = workTime.getStartTime();
            endTime = workTime.getEndTime();
        }

        return new WorkTime(startTime, endTime);
    }

    @Override
    public void _setContent(Object content) {
        workTime = (WorkTime) content;
        updateControls();
    }

    private void updateControls() {

        if (startTimeTextField.isVisible() != editMode || startTimeLabel.isVisible() == editMode) {
            startTimeTextField.setVisible(editMode);
            startEndTextFieldSeparatorLabel.setVisible(editMode);
            endTimeTextField.setVisible(editMode);
            startTimeLabel.setVisible(!editMode);
            startEndLabelSeparatorLabel.setVisible(!editMode);
            endTimeLabel.setVisible(!editMode);
        }

        if (workTime == null) {
            startTimeTextField.setText("00:00");
            endTimeTextField.setText("00:00");
            startTimeLabel.setText("00:00");
            endTimeLabel.setText("00:00");
            workDurationLabel.setText("00:00");

            return;
        }
        
        String startTimeString = DateTimeFormatUtils.localTimeFormat(workTime.getStartTime());
        String endTimeString = DateTimeFormatUtils.localTimeFormat(workTime.getEndTime());
        
        startTimeTextField.setText(startTimeString);
        endTimeTextField.setText(endTimeString);
        startTimeLabel.setText(startTimeString);
        endTimeLabel.setText(endTimeString);

        workDurationLabel.setText(DateTimeFormatUtils.durationFormat(workTime.getWorkDuration()));
    }
}
