/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package de.esterlino.timeplater.view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.JFrame;

/**
 *
 * @author Julien
 */
public class TimeplaterFrame extends JFrame {

    /**
     * Creates new form TimeplaterForm
     */
    public TimeplaterFrame() {
        initComponents();
        initialize();
    }

    private void initialize() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timeplaterPanel = new TimeplaterPanel();

        setBackground(new Color(255, 255, 102));
        setName("timePlaterFrame"); // NOI18N
        addComponentListener(new ComponentAdapter() {
            public void componentResized(ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().add(timeplaterPanel, BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        timeplaterPanel.setPreferredSize(evt.getComponent().getSize());
    }//GEN-LAST:event_formComponentResized


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private TimeplaterPanel timeplaterPanel;
    // End of variables declaration//GEN-END:variables
}
